### ISSUE TITLE
Build Failed for nativescript-sse plugin

### ISSUE THREAD

**Issue by VigneshraagavP** [triniwiz/nativescript-sse#11]
I have tried to create new project by the command 

> tns create SseApp

The app created and built successfully. Then installed the plugin nativescript-sse by the command 

> tns plugin add nativescript-sse

The plugin installed successfully and unfortunately the build gets failed. Please find the attached log file of the app build failure.

[log.txt](https://github.com/triniwiz/nativescript-sse/files/1920913/log.txt)

Please kindly help.

**Comment by triniwiz** [comment]
Can you please try updating again there was a fix release i believe that version you got had the typo

**Comment by VigneshraagavP** [comment]
The build gets succeeded and after I have followed the same link https://github.com/NickIliev/NS-Issues-2018/tree/master/others/t_1161642/app but when building the app I got some error like 

> Cannot read property 'extend' of undefined

Please find the attached log file and kindly look in to it also help us by solving the problem.

[log.txt](https://github.com/triniwiz/nativescript-sse/files/1922355/log.txt)

**Comment by triniwiz** [comment]
It doesn't find the class 🤔

**Comment by VigneshraagavP** [comment]
Am I missing something or any issue with the library?

**Comment by triniwiz** [comment]
I pushed a new update you can try updating before installing remove the platforms, node_modules and the package-lock it should guarantee a clean update

**Comment by VigneshraagavP** [comment]
As you said it is a clean update, now it works fine. Thank you.
