### ISSUE TITLE
JS ERROR TypeError: null is not an object (evaluating 'err.description')

### ISSUE THREAD

**Issue by terreb** [triniwiz/nativescript-sse#3]
I'm playing with the demo and connect to a test node sse server:

``` typescript
const SSE = require("sse-node"),
    app = require("express")();

app.get("/", (req, res) => {
    const client = SSE(req, res);
    client.send("Hello world!");
    client.onClose(() => console.log("Bye client!"));
});
app.listen(8000);
```

If for any reason the connection is closed (stopping nodejs server) I get this error:
file:///app/tns_modules/nativescript-sse/sse.js:31:31: JS ERROR TypeError: null is not an object (evaluating 'err.description')

The plugin version is 2.0.0

**Comment by terreb** [comment]
Also, I never get messages.

**Comment by triniwiz** [comment]
I will test and let you know because my demo worked last time i tested

**Comment by triniwiz** [comment]
https://github.com/triniwiz/nativescript-sse/commit/129db1fe1361d9510a0b2d1eec4ca5ae82786353
