### ISSUE TITLE
Error: Cannot read property 'on' of undefined.

### ISSUE THREAD

**Issue by eldadj** [triniwiz/nativescript-sse#5]
Hi, 
Trying to use this module in Nativescript and it gives the error: Cannot read property 'on' of undefined.

I fixed it by adding the line:

`this.events = new observable_1.Observable();`

between lines 8 and 9 of sse.android.js

specs.
version used: npm install nativescript-sse
node version: 7.3.0
npm version: 4.1.1
nativescript-sse version: 2.0.0

**Comment by 1u0n** [comment]
found the same problem, and same simple solution. This plugin's android version fails out of the box otherwise, which makes it difficult to depend on, isn't the repo creator active anymore?

**Comment by voanh** [comment]
i also found  same problem. have any idea to fix it?

**Comment by triniwiz** [comment]
Update coming soon

**Comment by h43z** [comment]
the 'data/observable' changed a little bit in NativeScript 3.0 and made this plugin unusable.
For me the above PR fixed the issue :) Same has to be done to ios code file I suspect.
